### ISSUE TITLE
Project (laravel) set up

### ISSUE THREAD

**Issue by eclipxe13** [phpcfdi/api-descarga-masiva#3]
- [X] Create Laravel application without front-end (main route should redirect to github repo)
- [X] PHP minimum version to 8.0
- [X] Add code standards
- [x] Add GitHub build workflow
- [x] Add contributing and development instructions

**Comment by AndreyPootMay** [comment]
No el `>=7.4`?

**Comment by eclipxe13** [comment]
No. PHP 7.4 termina el soporte activo el 2021-11-28 (en 2 meses). No tiene caso soportarlo en este momento.
